### ISSUE TITLE
How to specify explicit version for pdm-backend

### ISSUE THREAD

**Issue by gunmaden** [pdm-project/pdm-backend#260] opened 2024-09-20 08:23 UTC
Hi,
Is there any possibility to specify version explicitly for pdm-backend in pyproject.toml?

Changes such as [retrieving license files from 2.3.3 -> 2.4.0 could be breaking](https://github.com/pdm-project/pdm-backend/compare/2.3.3...2.4.0#diff-4dcc7e3bce9dc22290c57dc7ccb2d1a19d1bad16c7b5a133ba451b9ad659c1e5) so I want to update backend version by myself manually

```
[build-system]
requires = ["pdm-backend = 2.3.3"]
build-backend = "pdm.backend"
```

This option causing error
```
  ╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
      It contains an invalid requirement: 'pdm-backend = 2.3.3'
```

Another variations such as `["pdm-backend <= 2.3.3"]` or `["pdm-backend == 2.3.3"]` leads to downloaded pdm-backend v2.4.0

**Comment by frostming** [comment] 2024-09-20 08:38
```toml
[build-system]
requires = ["pdm-backend<2.4"]
build-backend = "pdm.backend"
```


> Another variations such as `["pdm-backend <= 2.3.3"]` or `["pdm-backend == 2.3.3"]` leads to downloaded pdm-backend v2.4.0

It's false, and they should work

**Comment by frostming** [comment] 2024-09-20 09:05
How do you build the project? an example project and steps to run would be helpful.

BTW, you should update the `license-files` field to follow PEP 639 since the old spec has been obsoleted.

**Comment by gunmaden** [comment] 2024-09-20 09:11
I'm trying to restore packages

Steps as follows:
1. Create new venv
2. Run `.venv/bin/python -m pip install . `

pyproject.toml
```
[project]
name = "sample-name"
description = "some description"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.12"
license-files = { paths = ["LICENSE.txt"] }
dependencies = [
    "build==1.0.3",
    "pdm==2.18.2",
    "pytest==7.4.3"
]

[tool.pdm.version]
source = "call"
getter = "get_version:run"

[tool.pdm.scripts]
test = "pytest"

[[tool.pdm.source]]
url = "https://some-internal-proget-feed"
verify_ssl = true
name = "external"

[[tool.pdm.source]]
url = "https://other-internal-proget-feed"
verify_ssl = true
name = "internal"

[build-system]
requires = ["pdm-backend<=2.3.3"]
build-backend = "pdm.backend"
```

> BTW, you should update the license-files field to follow PEP 639 since the old spec has been obsoleted.

Thanks. Planned soon

**Comment by frostming** [comment] 2024-09-20 09:23
Can't reproduce, `pip install` runs successfully with the version bound and fails if I remove the limit. The version specifier is obviously working

**Comment by frostming** [comment] 2024-09-20 09:26
Anyway, it is not related to pdm-backend project. Closing it now.

**Closed by frostming** 2024-09-20 09:26 UTC

**Comment by gunmaden** [comment] 2024-09-20 09:30
> Is it related to the dependencies? I test without any dependencies

seems like it occurs if dependencies does not have correct `build-system` block

removed our package dependency and it's works

Thanks a lot!
